### ISSUE TITLE
.setKeywords method fails on validation

### ISSUE THREAD

**Issue by k0d3d** [freakycue/mongoose-search-plugin#3]
I am using this plugin on an existing collection. As the documentation states, I run 
```javascript
  Model.setKeywords(function(err) {
    // ... 
  });
```
to initialize the keywords field, how ever I populated this collection using mongoimport which will not run any validation or middleware present on the schema. When Model.setKeywords run, I get validation error on fields that fail validation. I replaced  lines 133 - 136 with

```javascript
					doc.collection.insert(function(err) {
						if (err) console.log('[mongoose search plugin err] ', err, err.stack);
						done();
					});
``` 

I know this uses MongoDB native driver directly. It seems to solve my problem. I looked through the source code, I hope this doesnt break anything else. Is there a better way to solve this?

**Comment by freakycue** [comment]
@k0d3d could you provide example of the document, that cause this issue, error message and mongoose schema? Maybe It's possible to edit schema and solve this issue.

**Comment by k0d3d** [comment]
here is the schema. 
```javascript
var DsOnlineScehma = new Schema ({
  title : {type: String, default: '', required: true},
  sku : {type: String, required: true},
  price : {type: Number, required: true},
  regular_price : {type: Number, required: true},
  description : {type: String, required: true},
  categories : [{type: String, required: true}],
  tags : [{type: String, required: true}],
  imagesSrc: [{type: String, required: true}],
  attributes: [{
    'name': {type: String},
    'options': [{type: String}]
  }],
  currentPrice:{type: Number},
  created_at: {type: Date},
  updated_at: {type: Date},
  permalink: {type: String},
  product_id : {type: Number}
});
```
Here is the validation error

```
[mongoose search plugin err]  { [ValidationError: dsitem validation failed]
  message: 'dsitem validation failed',
  name: 'ValidationError',
  errors: 
   { description: 
      { [ValidatorError: Path `description` is required.]
        properties: [Object],
        message: 'Path `description` is required.',
        name: 'ValidatorError',
        kind: 'required',
        path: 'description',
        value: '' } } } ValidationError: dsitem validation failed
    at model.Document.invalidate 
```
I'm sorry I cannot provide any of the 'faulty' documents. Im sure with the error message you can deduce what is going on. The validation fails on fields / paths that have no value on the document or dont exist on the document but are required. Remember, I populated the collection using mongoimport

**Comment by freakycue** [comment]
@k0d3d I think this is not actually issue of the plugin. To solve this you can write migration script, that will  set default values for missing field.
